### ISSUE TITLE
Tìm hiểu về hệ quản trị cơ sở dữ liệu mongodb

### ISSUE THREAD

**Issue by hungnmZ** [manhung99/INT2208-7-2019#7]
- [x] Chọn hệ quản trị cơ sở dữ liệu MongoDB.
- [x] Cài đặt MongoDB.
- [x] Học cách tạo hệ quản trị cơ bản.
- [x] Học cách kết nối đến cơ sở dữ liệu bằng Node.js
- [x] Tìm hiểu về mongoose

**Comment by anhbros** [comment]
Đã hoàn thành
